Liga/Liga/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include(('administracion.urls', 'administracion', ), namespace='administracion'), ),
]

Liga/administracion/urls.py
from django.conf.urls import url, include
from administracion import views

urlpatterns=[
    #FRONTPAGE
    url(r'^$', views.index, name="index" ),
    url(r'^consultas/$', views.consultas, name="consultas" ),
    
    #ADMIN DASHBOARD
    url(r'^login/$', views.login, name="login" ),
    url(r'^cerrarSesion/$', views.cerrarSesion, name="cerrarSesion" ),
    url(r'^registrarUsuario/$', views.registrarUsuario, name="registrarUsuario" ),
    url(r'^dashboard/$', views.dashboard, name="dashboard" ),

    url(r'^agregarCatalogo/$', views.agregarCatalogo, name="agregarCatalogo" ),
    url(r'^actualizarCatalogo/$', views.actualizarCatalogo, name="actualizarCatalogo" ),
    url(r'^eliminarCatalogo/(?P<id>\d+)/$', views.eliminarCatalogo, name="eliminarCatalogo" ),

    url(r'^agregarItemCatalogo/$', views.agregarItemCatalogo, name="agregarItemCatalogo" ),
    url(r'^actualizarItemCatalogo/$', views.actualizarItemCatalogo, name="actualizarItemCatalogo" ),
    url(r'^eliminarItemCatalogo/(?P<id>\d+)/$', views.eliminarItemCatalogo, name="eliminarItemCatalogo" ),

    url(r'^agregarEquipo/$', views.agregarEquipo, name="agregarEquipo" ),
    url(r'^actualizarEquipo/$', views.actualizarEquipo, name="actualizarEquipo" ),
    url(r'^eliminarEquipo/(?P<id>\d+)/$', views.eliminarEquipo, name="eliminarEquipo" ),
    
    url(r'^agregarCampeonatoDeportivo/$', views.agregarCampeonatoDeportivo, name="agregarCampeonatoDeportivo" ),
    url(r'^actualizarCampeonatoDeportivo/$', views.actualizarCampeonatoDeportivo, name="actualizarCampeonatoDeportivo" ),
    url(r'^eliminarCampeonatoDeportivo/(?P<id>\d+)/$', views.eliminarCampeonatoDeportivo, name="eliminarCampeonatoDeportivo" ),

    url(r'^agregarSubcampeonato/$', views.agregarSubcampeonato, name="agregarSubcampeonato" ),
    url(r'^actualizarSubcampeonato/$', views.actualizarSubcampeonato, name="actualizarSubcampeonato" ),
    url(r'^eliminarSubcampeonato/(?P<id>\d+)/$', views.eliminarSubcampeonato, name="eliminarSubcampeonato" ),

    url(r'^agregarInscripcionEquipo/$', views.agregarInscripcionEquipo, name="agregarInscripcionEquipo" ),
    url(r'^eliminarInscripcionEquipo/(?P<id>\d+)/$', views.eliminarInscripcionEquipo, name="eliminarInscripcionEquipo" ),
    url(r'^consultaEquiposSubcampeonato/$', views.consultaEquiposSubcampeonato, name="consultaEquiposSubcampeonato" ), #consulta los equipos, dado un subcampeonato (masculino/femenino)

    url(r'^agregarJugador/$', views.agregarJugador, name="agregarJugador" ),
    url(r'^actualizarJugador/$', views.actualizarJugador, name="actualizarJugador" ),
    url(r'^eliminarJugador/(?P<id>\d+)/$', views.eliminarJugador, name="eliminarJugador" ),

    url(r'^agregarPaseDeportivo/$', views.agregarPaseDeportivo, name="agregarPaseDeportivo" ),
    url(r'^eliminarPaseDeportivo/(?P<id>\d+)/$', views.eliminarPaseDeportivo, name="eliminarPaseDeportivo" ),
    url(r'^consultarEquiposInscritosEnCampeonatoDeportivo/$', views.consultarEquiposInscritosEnCampeonatoDeportivo, name="consultarEquiposInscritosEnCampeonatoDeportivo" ), #retorna los equipos deportivos inscritos en un determinados campeonato deportivo
    url(r'^consultaSubcampeonatosActuales/$', views.consultaSubcampeonatosActuales, name="consultaSubcampeonatosActuales" ), #retorna los campeonatos deportivos actuales

    url(r'^agregarInscripcionJugador/$', views.agregarInscripcionJugador, name="agregarInscripcionJugador" ), 
    url(r'^eliminarInscripcionJugador/$', views.eliminarInscripcionJugador, name="eliminarInscripcionJugador" ), 
    url(r'^consultarEquiposInscritosDadoSubcampeonato/$', views.consultarEquiposInscritosDadoSubcampeonato, name="consultarEquiposInscritosDadoSubcampeonato" ),  #retorna los equipos inscritos dentro de un subcampeonato, dado el subcampeonato
    url(r'^consultarJugadoresDadoSubcampeonato/$', views.consultarJugadoresDadoSubcampeonato, name="consultarJugadoresDadoSubcampeonato" ),  #retorna los jugadores dependeindo del subcampeonato seleccionado




    url(r'^agregarEncuentrosDeportivos/$', views.agregarEncuentrosDeportivos, name="agregarEncuentrosDeportivos" ),



    url(r'^subirListado/$', views.subirListado, name="subirListado" ),
    url(r'^eliminarFechaDeportiva/(?P<idFecha>\d+)/$', views.eliminarFechaDeportiva, name="eliminarFechaDeportiva" ),
    url(r'^actualizarFechaDeportiva/$', views.actualizarFechaDeportiva, name="actualizarFechaDeportiva" ),
    url(r'^administrarFechasDeportivas/$', views.administrarFechasDeportivas, name="administrarFechasDeportivas" ),
    url(r'^administrarFechas/$', views.administrarFechas, name="administrarFechas" ),
    
    url(r'^eliminarFecha/(?P<idFecha>\d+)/$', views.eliminarFecha, name="eliminarFecha" ),
    url(r'^actualizarFecha/$', views.actualizarFecha, name="actualizarFecha" ),
    url(r'^administrarHorarios/$', views.administrarHorarios, name="administrarHorarios" ),
    url(r'^actualizarHorario/$', views.actualizarHorario, name="actualizarHorario" ),
    url(r'^eliminarHorario/(?P<idHorario>\d+)/$', views.eliminarHorario, name="eliminarHorario" ),
    url(r'^administrarHoras/$', views.administrarHoras, name="administrarHoras" ),
    url(r'^actualizarHora/$', views.actualizarHora, name="actualizarHora" ),    
    url(r'^eliminarHora/(?P<idHora>\d+)/$', views.eliminarHora, name="eliminarHora" ),
    url(r'^consultaHoras/$', views.consultaHoras, name="consultaHoras" ),
    url(r'^consultaEquipos/$', views.consultaEquipos, name="consultaEquipos" ),
    url(r'^prueba/$', views.prueba, name="prueba" ),
]

Liga/templates/frontpage/consultas.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static "estilo1.css" %}">
  <title>Document</title>
</head>

<body>
  <section id="encabezado">
    <section id="navPrincipal" class="row text-center">
      <h1 id="titulo" class="col-sm-4 d-inline-block">Liga Deportiva Parroquial de Nono</h1>
      <section id="links" class="col-sm-8 d-inline-block">
        <a href="">LA LIGA</a>
        <a href="">LA DIRECTIVA</a>
        <a href="">SERVICIOS</a>
        <a href="">ESPACIOS DEPORTIVOS</a>
        <a href="">EL DEPORTE</a>
        <a href="">CONSULTAS</a>
        <a href="">LOGIN</a>
      </section>
    </section>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        {% if listaFechas %}
          {% for fecha in listaFechas %} 
            <div class="carousel-item active">
            <img class="" src="{% static "images/estadio.jpeg"%}" alt="First slide">
            <div class="carousel-caption d-md-block">
              <h5 class="text-left">¡PILAS CON LA PROGRAMACIÓN!</h5>
              <section class="descripcionCarousel">
                <h5 class="text-left">Fecha de fuego : {{fecha.0.fecha.fecha}}</h5>
                <h5 class="text-left text-capitalize">{{fecha.0.fecha.fechaDeportiva}}</h5>           
              </section>            
              <table id="bootstrap-data-table" class="table table-hover borderless tablaEncuentrosDeportivosSemanales">
                <thead>
                  <tr class="text-center">
                    <th>HORA</th>
                    <th>EQUIPO 1</th>
                    <th>EQUIPO 2</th>
                  </tr>
                </thead>
                <tbody>
                {% for encuentroDeportivo in fecha %}
                  <tr class="text-center">
                    <td hidden> {{ encuentroDeportivo.id }}</td>
                    <td>{{ encuentroDeportivo.hora }}</td>
                    <td>{{ encuentroDeportivo.equipo1 }}</td>
                    <td>{{ encuentroDeportivo.equipo2 }}</td>
                  </tr>
                {% endfor %}
                </tbody>
              </table>
            </div>
          </div>
          {% endfor %}
        {% endif %}
        



        <div class="carousel-item">
          <img class="" src="{% static "images/estadio.jpeg"%}" alt="Second slide">
          <div class="carousel-caption d-md-block">
            <p>Trabajamos para traerte un nuevo espacio deportivo!</p>
          </div>
        </div>
        <div class="carousel-item">
          <img class="" src="{% static "images/estadio.jpeg"%}" alt="Third slide">
          <div class="carousel-caption d-md-block">
            <h5>...</h5>
            <p>...</p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </section>
  
  <section>
    <h1>liga</h1>
  </section>

  <script type="text/javascript">
    $('.carousel').carousel({
      interval: 2000
    })
  </script>






</body>

</html>

Liga/templates/frontpage/index.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="{% static "estilo1.css" %}">
  <title>Document</title>
</head>

<body>
  <section id="encabezado">
    <section id="navPrincipal" class="col-sm-12 text-center">
      <h1 id="titulo" class="col-sm-12 d-block">Liga Deportiva Parroquial "San Miguel de Nono"</h1>
      <section id="links" class="sol-sm-12">
        <a href="">LA LIGA</a>
        <a href="">LA DIRECTIVA</a>
        <a href="">SERVICIOS</a>
        <a href="">ESPACIOS DEPORTIVOS</a>
        <a href="">EL DEPORTE</a>
        <a href="{% url 'administracion:consultas'%}">CONSULTAS</a>
        <a href="">LOGIN</a>
      </section>
    </section>
    <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
      <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner">
        <div class="carousel-item active">
          <img class="" src="{% static "images/estadio.jpeg"%}" alt="First slide">
          <div class="carousel-caption d-md-block">
            <h5>Un nuevo estadio!</h5>
            <p>Trabajamos para traerte un nuevo espacio deportivo!</p>
          </div>
        </div>
        <div class="carousel-item">
          <img class="" src="{% static "images/estadio.jpeg"%}" alt="Second slide">
          <div class="carousel-caption d-md-block">
            <h5>Un nuevo estadio!</h5>
            <p>Trabajamos para traerte un nuevo espacio deportivo!</p>
          </div>
        </div>
        <div class="carousel-item">
          <img class="" src="{% static "images/estadio.jpeg"%}" alt="Third slide">
          <div class="carousel-caption d-md-block">
            <h5>...</h5>
            <p>...</p>
          </div>
        </div>
      </div>
      <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div>
  </section>
  <section>
    <h1>liga</h1>
  </section>
  <section>
    <h1>liga</h1>
  </section>

  <script type="text/javascript">
    $('.carousel').carousel()
  </script>






</body>

</html>