Liga/Liga/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
    path(r'', include(('administracion.urls', 'administracion', ), namespace='administracion'), ),
]

Liga/administracion/urls.py
from django.conf.urls import url, include
from administracion import views

urlpatterns=[
    #FRONTPAGE
    url(r'^$', views.index, name="index" ),
    url(r'^consultas/$', views.consultas, name="consultas" ),
    
    #ADMIN DASHBOARD
    url(r'^login/$', views.login, name="login" ),
    url(r'^cerrarSesion/$', views.cerrarSesion, name="cerrarSesion" ),
    url(r'^registrarUsuario/$', views.registrarUsuario, name="registrarUsuario" ),
    url(r'^dashboard/$', views.dashboard, name="dashboard" ),

    url(r'^agregarCatalogo/$', views.agregarCatalogo, name="agregarCatalogo" ),
    url(r'^actualizarCatalogo/$', views.actualizarCatalogo, name="actualizarCatalogo" ),
    url(r'^eliminarCatalogo/(?P<id>\d+)/$', views.eliminarCatalogo, name="eliminarCatalogo" ),

    url(r'^agregarItemCatalogo/$', views.agregarItemCatalogo, name="agregarItemCatalogo" ),
    url(r'^actualizarItemCatalogo/$', views.actualizarItemCatalogo, name="actualizarItemCatalogo" ),
    url(r'^eliminarItemCatalogo/(?P<id>\d+)/$', views.eliminarItemCatalogo, name="eliminarItemCatalogo" ),

    url(r'^agregarEquipo/$', views.agregarEquipo, name="agregarEquipo" ),
    url(r'^actualizarEquipo/$', views.actualizarEquipo, name="actualizarEquipo" ),
    url(r'^eliminarEquipo/(?P<id>\d+)/$', views.eliminarEquipo, name="eliminarEquipo" ),
    
    url(r'^agregarCampeonatoDeportivo/$', views.agregarCampeonatoDeportivo, name="agregarCampeonatoDeportivo" ),
    url(r'^actualizarCampeonatoDeportivo/$', views.actualizarCampeonatoDeportivo, name="actualizarCampeonatoDeportivo" ),
    url(r'^eliminarCampeonatoDeportivo/(?P<id>\d+)/$', views.eliminarCampeonatoDeportivo, name="eliminarCampeonatoDeportivo" ),

    url(r'^agregarSubcampeonato/$', views.agregarSubcampeonato, name="agregarSubcampeonato" ),
    url(r'^actualizarSubcampeonato/$', views.actualizarSubcampeonato, name="actualizarSubcampeonato" ),
    url(r'^eliminarSubcampeonato/(?P<id>\d+)/$', views.eliminarSubcampeonato, name="eliminarSubcampeonato" ),

    url(r'^agregarInscripcionEquipo/$', views.agregarInscripcionEquipo, name="agregarInscripcionEquipo" ),
    url(r'^eliminarInscripcionEquipo/(?P<id>\d+)/$', views.eliminarInscripcionEquipo, name="eliminarInscripcionEquipo" ),
    url(r'^consultaEquiposSubcampeonato/$', views.consultaEquiposSubcampeonato, name="consultaEquiposSubcampeonato" ), #consulta los equipos, dado un subcampeonato (masculino/femenino)

    url(r'^agregarJugador/$', views.agregarJugador, name="agregarJugador" ),
    url(r'^actualizarJugador/$', views.actualizarJugador, name="actualizarJugador" ),
    url(r'^eliminarJugador/(?P<id>\d+)/$', views.eliminarJugador, name="eliminarJugador" ),

    url(r'^agregarPaseDeportivo/$', views.agregarPaseDeportivo, name="agregarPaseDeportivo" ),
    url(r'^eliminarPaseDeportivo/(?P<id>\d+)/$', views.eliminarPaseDeportivo, name="eliminarPaseDeportivo" ),
    url(r'^consultarEquiposInscritosEnCampeonatoDeportivo/$', views.consultarEquiposInscritosEnCampeonatoDeportivo, name="consultarEquiposInscritosEnCampeonatoDeportivo" ), #retorna los equipos deportivos inscritos en un determinados campeonato deportivo
    url(r'^consultaSubcampeonatosActuales/$', views.consultaSubcampeonatosActuales, name="consultaSubcampeonatosActuales" ), #retorna los campeonatos deportivos actuales

    url(r'^agregarInscripcionJugador/$', views.agregarInscripcionJugador, name="agregarInscripcionJugador" ), 
    url(r'^eliminarInscripcionJugador/$', views.eliminarInscripcionJugador, name="eliminarInscripcionJugador" ), 
    url(r'^consultarEquiposInscritosDadoSubcampeonato/$', views.consultarEquiposInscritosDadoSubcampeonato, name="consultarEquiposInscritosDadoSubcampeonato" ),  #retorna los equipos inscritos dentro de un subcampeonato, dado el subcampeonato
    url(r'^consultarJugadoresDadoSubcampeonato/$', views.consultarJugadoresDadoSubcampeonato, name="consultarJugadoresDadoSubcampeonato" ),  #retorna los jugadores dependeindo del subcampeonato seleccionado




    url(r'^agregarEncuentrosDeportivos/$', views.agregarEncuentrosDeportivos, name="agregarEncuentrosDeportivos" ),



    url(r'^subirListado/$', views.subirListado, name="subirListado" ),
    url(r'^eliminarFechaDeportiva/(?P<idFecha>\d+)/$', views.eliminarFechaDeportiva, name="eliminarFechaDeportiva" ),
    url(r'^actualizarFechaDeportiva/$', views.actualizarFechaDeportiva, name="actualizarFechaDeportiva" ),
    url(r'^administrarFechasDeportivas/$', views.administrarFechasDeportivas, name="administrarFechasDeportivas" ),
    url(r'^administrarFechas/$', views.administrarFechas, name="administrarFechas" ),
    
    url(r'^eliminarFecha/(?P<idFecha>\d+)/$', views.eliminarFecha, name="eliminarFecha" ),
    url(r'^actualizarFecha/$', views.actualizarFecha, name="actualizarFecha" ),
    url(r'^administrarHorarios/$', views.administrarHorarios, name="administrarHorarios" ),
    url(r'^actualizarHorario/$', views.actualizarHorario, name="actualizarHorario" ),
    url(r'^eliminarHorario/(?P<idHorario>\d+)/$', views.eliminarHorario, name="eliminarHorario" ),
    url(r'^administrarHoras/$', views.administrarHoras, name="administrarHoras" ),
    url(r'^actualizarHora/$', views.actualizarHora, name="actualizarHora" ),    
    url(r'^eliminarHora/(?P<idHora>\d+)/$', views.eliminarHora, name="eliminarHora" ),
    url(r'^consultaHoras/$', views.consultaHoras, name="consultaHoras" ),
    url(r'^consultaEquipos/$', views.consultaEquipos, name="consultaEquipos" ),
    url(r'^prueba/$', views.prueba, name="prueba" ),
]

Liga/templates/formularioCampeonatosDeportivos.html
{% extends 'dashboardBase.html' %} 
{% load static %}
{% block areaTrabajo %}

<div class="breadcrumbs mb-1">
    <div class="col-sm-4">
        <div class="page-header float-left">
            <div class="page-title">
                <h1>Administrar Campeonatos</h1>
            </div>
        </div>
    </div>
    <div class="col-sm-8">
        <div class="page-header float-right">
            <div class="page-title">
                <ol class="breadcrumb text-right">
                    <li class="active">Campeonato</li>
                    <li class="active">Administrar Campeonatos</li>
                </ol>
            </div>
        </div>
    </div>
</div>

{% if formularioAgregarCampeonatoDeportivo.errors %}
<div class="col-sm-12">
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h6>No ha sido posible almacenar la información ingresada debido a los siguientes errores:</h6>
    {% for field in formularioAgregarCampeonatoDeportivo %}
        {% if field.errors %}
            {% for error in field.errors %}
                <p><strong>Campo en conflicto: </strong>{{ field.name }}</p>
                <p><strong>Descripción: </strong><span class="text-lowercase">{{ error|escape }}</span></p>
            {% endfor %}
        {% endif %}
    {% endfor %}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>
</div>
{% endif %}

<div class="content mt-1">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-xs-5 col-sm-5">
                <div class="card">
                    <div class="card-header">
                        <strong>Agregar Campeonato Deportivo</strong>
                    </div>
                    <form action="{% url 'administracion:agregarCampeonatoDeportivo' %}" method="POST" class="card-body card-block" autocomplete="off">
                        {% csrf_token %}
                        <div class="form-group col-sm-12">
                            <label for="">Nombre del campeonato</label>
                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <i class="fa fa-pencil"></i>
                                    </div>
                                    {{formularioAgregarCampeonatoDeportivo.nombre}}                                    
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-sm-12">
                            <label for="">Fecha de inicio</label>
                            <div class="form-group">
                                <div class="input-group">
                                    <div class="input-group-addon">
                                        <i class="fa fa-calendar"></i>
                                    </div>
                                    {{formularioAgregarCampeonatoDeportivo.fechaInicio}}
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-sm-12">
                            <label for="">Predefinido</label>
                            {{formularioAgregarCampeonatoDeportivo.predefinido}}
                        </div>
                        <div class="col-lg-12 text-center">
                            <button class="btn btn-success" type="submit">Guardar</button>
                            <button class="btn btn-success" type="reset">Cancelar</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-xs-7 col-sm-7">
                <div class="card">
                    <div class="card-header">
                        <strong>Campeonatos Deportivos Registrados</strong>
                    </div>
                    <div class="card-body card-block">
                        {% if campeonatosDeportivosRegistrados %}
                            <table id="bootstrap-data-table" class="table table-striped tableFechas">
                                    <thead>
                                      <tr class="text-center row">
                                        <th class="col-sm-5">Nombre</th>
                                        <th class="col-sm-3">Fecha inicio</th>
                                        <th class="col-sm-2">Pred.</th>
                                        <th class="col-sm-1"></th>
                                        <th class="col-sm-1"></th>
                                      </tr>
                                    </thead>
                                    <tbody>
                                    {% for campeonato in campeonatosDeportivosRegistrados %}
                                      <tr class="text-center row">
                                        <td hidden> {{ campeonato.id }}</td>
                                        <td class="col-sm-5"> {{ campeonato }}</td>
                                        <td class="col-sm-3"> {{ campeonato.fechaInicio.isoformat }}</td>
                                        <td class="col-sm-2"> {{ campeonato.predefinido }}</td>
                                        <td class="col-sm-1"><a onclick="setDatosCampeonatoDeportivo('{{ campeonato.id }}','{{ campeonato.nombre }}', '{{ campeonato.fechaInicio.isoformat}}', '{{ campeonato.predefinido}}')" data-toggle="modal" data-target="#largeModal"><img src="{% static "images/update.png"%}"></a></td>
                                        <td class="col-sm-1"><a href="{% url 'administracion:eliminarCampeonatoDeportivo' campeonato.id %}"><img src="{% static "images/remove.png"%}"></a></td>
                                      </tr>
                                    {% endfor %}
                                    </tbody>
                            </table>
                        {% endif %}
                    </div>
                </div>               
            </div>
        </div>
    </div>
</div>

<div class="modal fade" id="largeModal" tabindex="-1" role="dialog" aria-labelledby="largeModalLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header mb-3">
                <h5 class="modal-title" id="largeModalLabel">Modificar Fecha</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            {% if formularioActualizarCampeonatoDeportivo.errors %}
                <div class="col-sm-12">
                    <div class="alert alert-danger alert-dismissible fade show" role="alert">
                        <h6>No ha sido posible almacenar la información ingresada debido a los siguientes errores:</h6>
                    {% for field in formularioActualizarCampeonatoDeportivo %}
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <p><strong>Campo en conflicto: </strong>{{ field.name }}</p>
                                <p><strong>Descripción: </strong><span class="text-lowercase">{{ error|escape }}</span></p>
                            {% endfor %}
                        {% endif %}
                    {% endfor %}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    </div>
                </div>
            {% endif %}
            <form action="{% url 'administracion:actualizarCampeonatoDeportivo' %}" method="POST" autocomplete="off">
                {% csrf_token %}
                <div class="form-group col-sm-12">
                    {{formularioActualizarCampeonatoDeportivo.id.as_hidden }}
                    <label for="">Nombre del campeonato</label>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-pencil"></i>
                            </div>
                            {{formularioActualizarCampeonatoDeportivo.nombre}}
                        </div>
                    </div>
                </div>
                <div class="form-group col-sm-12">
                    <label for="">Fecha de inicio</label>
                    <div class="form-group">
                        <div class="input-group">
                            <div class="input-group-addon">
                                <i class="fa fa-calendar"></i>
                            </div>
                            {{formularioActualizarCampeonatoDeportivo.fechaInicio}}
                        </div>
                    </div>
                </div>
                <div class="form-group col-sm-12">
                    <label for="">Predefinido</label>
                     {{formularioActualizarCampeonatoDeportivo.predefinido}}
                </div>
                <div class="modal-footer">
                    <button id="sub" class="btn btn-success" type="submit">Guardar</button>
                    <button class="btn btn-success" data-dismiss="modal" aria-label="Close">Cancelar</button>
                </div>
            </form>
        </div>
    </div>
</div>


{% if formularioActualizarCampeonatoDeportivo.errors %}
<script>
    $(function(){
        $('#largeModal').modal('show');
    })
</script>
{% endif %}

<script>
    $(function(){
        $('#id_formularioAgregarCampeonatoDeportivo-fechaInicio').datepicker({ dateFormat: 'yy-mm-dd' }),
        $('#id_formularioActualizarCampeonatoDeportivo-fechaInicio').datepicker({ dateFormat: 'yy-mm-dd' })
    });

    function setDatosCampeonatoDeportivo(id, nombre, fechaInicio, predefinido){
        $('#id_formularioActualizarCampeonatoDeportivo-id').val(id);
        $('#id_formularioActualizarCampeonatoDeportivo-nombre').val(nombre);
        $('#id_formularioActualizarCampeonatoDeportivo-fechaInicio').val(fechaInicio);
        if(predefinido=='True'){
            $('#id_formularioActualizarCampeonatoDeportivo-predefinido').prop( "checked", true )
        }else{
            $('#id_formularioActualizarCampeonatoDeportivo-predefinido').prop( "checked", false )
        }
    }

</script>


{% endblock %}

Liga/templates/formularioInscripcionesEquipo.html
{% extends 'dashboardBase.html' %} 
{% load static %}
{% block areaTrabajo %}

<div class="breadcrumbs mb-1">
    <div class="col-sm-4">
        <div class="page-header float-left">
            <div class="page-title">
                <h1>Administrar Subcampeonatos</h1>
            </div>
        </div>
    </div>
    <div class="col-sm-8">
        <div class="page-header float-right">
            <div class="page-title">
                <ol class="breadcrumb text-right">
                    <li class="active">Campeonato</li>
                    <li class="active">Administrar Subcampeonatos</li>
                </ol>
            </div>
        </div>
    </div>
</div>

{% if formularioAgregarInscripcionEquipo.errors %}
<div class="col-sm-12">
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <h6>No ha sido posible almacenar la información ingresada debido a los siguientes errores:</h6>
    {% for field in formularioAgregarInscripcionEquipo %}
        {% if field.errors %}
            {% for error in field.errors %}
                <p><strong>Campo en conflicto: </strong>{{ field.name }}</p>
                <p><strong>Descripción: </strong><span class="text-lowercase">{{ error|escape }}</span></p>
            {% endfor %}
        {% endif %}
    {% endfor %}
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>
    </div>
</div>
{% endif %}

<div class="content mt-1">
    <div class="animated fadeIn">
        <div class="row">
            <div class="col-xs-5 col-sm-5">
                <div class="card">
                    <div class="card-header">
                        <strong>Agregar Subcampeonato</strong>
                    </div>
                    <form action="{% url 'administracion:agregarInscripcionEquipo' %}" method="POST" class="card-body card-block" autocomplete="off">
                        {% csrf_token %}
                        <div class="form-group col-sm-12">
                            <label for=""></label>
                            <label for="">Modalidad</label>
                            <div class="form-group">
                                <div class="input-group">
                                    {{formularioAgregarInscripcionEquipo.subcampeonato}}
                                </div>
                            </div>
                        </div>
                        <div class="form-group col-sm-12">
                            <label for=""></label>
                            <label for="">Equipo</label>
                            <div class="form-group">
                                <div class="input-group">
                                    {{formularioAgregarInscripcionEquipo.equipo}}
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-12 text-center">
                            <button class="btn btn-success" type="submit">Guardar</button>
                            <button class="btn btn-success" type="reset">Cancelar</button>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-xs-7 col-sm-7">
                <div class="card">
                    <div class="card-header">
                        <strong>Inscripciones Registradas</strong>
                    </div>
                    <div class="card-body card-block">
                        {% if inscripcionesEquipoRegistradas %}
                            <table id="bootstrap-data-table" class="table table-striped tableFechas">
                                    <thead>
                                      <tr class="text-center row">
                                        <th class="col-sm-4">Subcampeonato</th>
                                        <th class="col-sm-7">Equipo</th>
                                        <th class="col-sm-1"></th>
                                      </tr>
                                    </thead>
                                    <tbody>
                                    {% for inscripcionEquipo in inscripcionesEquipoRegistradas %}
                                      <tr class="text-center row">
                                        <td hidden> {{ inscripcionEquipo.id }}</td>
                                        <td class="col-sm-4"> {{ inscripcionEquipo.subcampeonato.modalidad }}</td>
                                        <td class="col-sm-7"> {{ inscripcionEquipo.equipo.nombre }}</td>
                                        <td class="col-sm-1"><a href="{% url 'administracion:eliminarInscripcionEquipo' inscripcionEquipo.id %}"><img src="{% static "images/remove.png"%}"></a></td>
                                      </tr>
                                    {% endfor %}
                                    </tbody>
                            </table>
                        {% endif %}
                    </div>
                </div>               
            </div>
        </div>
    </div>
</div>

<script>

    $( function() {
        eliminarOptionsSubcampeonato();
        consultaSubcampeonatosActuales();
        idSubcampeonato = $('#id_formularioAgregarInscripcionEquipo-subcampeonato option:selected').val();
        if(idSubcampeonato==''){
            $('#id_formularioAgregarInscripcionEquipo-equipo').prop('disabled', true);
        }
    } );    

    $('#id_formularioAgregarInscripcionEquipo-subcampeonato').change(function(event) {
        idSubcampeonato = $('#id_formularioAgregarInscripcionEquipo-subcampeonato option:selected').val();
        if(idSubcampeonato!=''){
            eliminarOptionsEquipo();
            $('#id_formularioAgregarInscripcionEquipo-equipo').prop('disabled', false);
            consultaEquipos();
        }else{
            $('#id_formularioAgregarInscripcionEquipo-equipo').prop('disabled', true);
            eliminarOptionsEquipo();
        }
    });

    function consultaSubcampeonatosActuales(){
        $.ajax({
        type: 'POST',
        dataType: 'json',
        async: false,
        url: '{% url "administracion:consultaSubcampeonatosActuales"%}',
        data: {
            csrfmiddlewaretoken: '{{ csrf_token }}'
        },
        success: function (data) {
            alert(data);
            equipos = JSON.parse(data);
            for (var k = 0; k < Object.keys(equipos).length; k++) {
                agregarOptionsSubcampeonato(equipos[k].id, equipos[k].nombre);
            }
        },
        error: function(err){
            alert("Error!");
        }
        });
    }

    function eliminarOptionsSubcampeonato(){
        $("#id_formularioAgregarInscripcionEquipo-subcampeonato option").each(function() {
            $(this).remove();
        });

        $("#id_formularioAgregarInscripcionEquipo-subcampeonato").append($('<option>')
            .val('')
            .text("Seleccionar")                           
        );
    }

    function agregarOptionsSubcampeonato(id, nombre){
        $("#id_formularioAgregarInscripcionEquipo-subcampeonato").append($('<option>')
            .val(id)
            .text(nombre)                           
        );
    }



    function consultaEquipos(){
        idSubcampeonato = $('#id_formularioAgregarInscripcionEquipo-subcampeonato option:selected').val();
        $.ajax({
        type: 'POST',
        dataType: 'json',
        async: false,
        url: '{% url "administracion:consultaEquiposSubcampeonato"%}',
        data: {
            csrfmiddlewaretoken: '{{ csrf_token }}',
            idSubcampeonato: idSubcampeonato,
        },
        success: function (data) {
            equipos = JSON.parse(data);
            for (var k = 0; k < Object.keys(equipos).length; k++) {
                agregarOptionsEquipo(equipos[k].idEquipo, equipos[k].equipo);
            }
        },
        error: function(err){
            alert("Error!");
        }
        });
    }

    function eliminarOptionsEquipo(){
        $("#id_formularioAgregarInscripcionEquipo-equipo option").each(function() {
            $(this).remove();
        });

        $("#id_formularioAgregarInscripcionEquipo-equipo").append($('<option>')
            .val('')
            .text("Seleccionar")                           
        );
    }

    function agregarOptionsEquipo(idEquipo, nombreEquipo){
        $("#id_formularioAgregarInscripcionEquipo-equipo").append($('<option>')
            .val(idEquipo)
            .text(nombreEquipo)                           
        );
    }

</script>


{% endblock %}

Liga/templates/formularioLogin.html
{% extends 'baseFormulario.html' %}

{% block formulario %}
    <section class="titulo">
        <h2>Liga Deportiva Parroquial de Nono</h2>
    </section>
    <section class="subtitulo">
        <p>Autenticación de usuarios</p>
    </section>
    <div class="login-form">
        <form action="./" method="POST" class="col-md-12 t-center">
            {% csrf_token %}
            {{formularioLogin.username.label_tag }}
            {{formularioLogin.username}}
            {{formularioLogin.password.label_tag }}
            {{formularioLogin.password}}

            {% if messages %}
                <section class="seccionErrores">

                    {% if field.errors %}
                        {% for field in formularioLogin %}
                            {% if field.errors %}
                                <li>{{ field.label }}: {{ field.errors|striptags }}</li>
                            {% endif %}
                        {% endfor %}
                    {% else %}
                        {% for message in messages %}
                            <li>{{ message }}</li>
                        {% endfor %}
                    {% endif %}
                </section>
            {% endif %}

            <button type="submit" class="btn btn-rojo btn-flat m-b-30 m-t-30">Sign in</button>
        </form>
    </div>
{% endblock %}

Liga/templates/formularioRegistro.html
{% extends 'baseFormulario.html' %}

{% block formulario %}
    <section class="titulo">
        <h2>Liga Deportiva Parroquial de Nono</h2>
    </section>
    <section class="subtitulo">
        <p>Registrar nuevo usuario</p>
    </section>
    <div class="login-form">
        <form action="./" method="POST" class="col-md-12 t-center">
            {% csrf_token %}
                {{formularioCredencial.name.label_tag }}
                {{formularioCredencial.name }}
                {{formularioCredencial.lastname.label_tag }}
                {{formularioCredencial.lastname}} 
                {{formularioCredencial.username.label_tag }}
                {{formularioCredencial.username}}
                {{formularioCredencial.email.label_tag }}
                {{formularioCredencial.email}}                               
                {{formularioCredencial.tipoUsuario.label_tag }}
                {{formularioCredencial.tipoUsuario}}
                {{formularioCredencial.password.label_tag }}
                {{formularioCredencial.password}}
                
                {% if messages %}
                    <section class="seccionErrores">
                        {% for field in formularioCredencial %}
                            {% if field.errors %}
                                <li>{{ field.label }}: {{ field.errors|striptags }}</li>
                            {% endif %}
                        {% endfor %}
                    </section>
                {% endif %}

            <button type="submit" class="btn btn-rojo btn-flat m-b-30 m-t-30">Guardar</button>
        </form>
    </div>
{% endblock %}

Liga/templates/head.html
{% block head %}
<!doctype html>
{% load static %}
<html class="no-js" lang="">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Registro</title>
    <meta name="description" content="Sufee Admin - HTML5 Admin Template">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="apple-touch-icon" href="apple-icon.png">
    <link rel="shortcut icon" href="favicon.ico">
    <link rel="stylesheet" href="{% static "assets/css/normalize.css"%}">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static "assets/css/font-awesome.min.css"%}">
    <link rel="stylesheet" href="{% static "assets/css/themify-icons.css"%}">
    <link rel="stylesheet" href="{% static "assets/css/flag-icon.min.css"%}">
    <link rel="stylesheet" href="{% static "assets/css/cs-skin-elastic.css"%}">
    <link rel="stylesheet" href="{% static "assets/scss/style.css"%}">
    <link href="{% static "assets/css/lib/vector-map/jqvmap.min.css"%}" rel="stylesheet">
    <link href='https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800' rel='stylesheet' type='text/css'>
    <link rel="stylesheet" href="{% static "estilo.css" %}">
{% endblock %}